library("shiny")
library("shinyWidgets")
library("stringr")
library("data.table")
library("bslib")
library("vroom")
library("plotly")
library("scales")
library("htmltools")
library("sf")
#library("regioniItalia") 
library("dplyr")
library("purrr")
library("readr")
library("reactable")
library("DescTools") #RoundTo
library("crosstalk")
library("leaflet")
library("gfonts")
library("fontawesome")
library("bsplus") #tooltips


source("./R/tabella.R")
source("./R/grafici.R")
source("./R/mappa.R")
source("./R/modulesUIServer.R")
#source("./R/trasformaAna.R")
month.name<-c("Gennaio","Febbraio","Marzo","Aprile","Maggio","Giugno","Luglio","Agosto","Settembre","Ottobre","Novembre","Dicembre")
season.name<-c("Inverno","Primavera","Estate","Autunno")
